import { getTranslations } from "next-intl/server";

import { APPEARANCE_PRESETS, COLOR_PRESET_OPTIONS } from "@/lib/wishlist-appearance";

/**
 * Mini preset cards generated by mapping over `COLOR_PRESET_OPTIONS` /
 * `APPEARANCE_PRESETS` (never a hardcoded preset list) so this section can't
 * drift from what the product actually offers — it automatically picks up
 * `paper`/`chalk` once the sibling appearance-presets phase merges. Labels
 * come from the `Settings` namespace via the same `t(presetTheme.labelKey)`
 * pattern `settings-form.tsx` already uses; this only reads that namespace,
 * it doesn't restructure it.
 */
export async function PresetsShowcase() {
  const t = await getTranslations("HomePage");
  const tSettings = await getTranslations("Settings");

  return (
    <section className="px-4 py-20">
      <div className="container mx-auto max-w-5xl text-center">
        <h2 className="font-display text-2xl text-(--sk-text) sm:text-3xl">
          {t("presetsTitle")}
        </h2>
        <p className="mx-auto mt-4 max-w-2xl font-hand text-base text-(--sk-text-muted) sm:text-lg">
          {t("presetsDesc")}
        </p>
        <div className="mt-10 grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-5">
          {COLOR_PRESET_OPTIONS.map((preset) => {
            const presetTheme = APPEARANCE_PRESETS[preset];

            return (
              <div
                key={preset}
                className="sketch sketch-tight sketch-interactive flex flex-col items-center gap-3 bg-(--sk-surface) p-4"
              >
                <div className="flex items-center gap-1" aria-hidden="true">
                  <span
                    className="h-5 w-5 rounded-full border-[1.6px] border-(--sk-line)"
                    style={{ backgroundColor: presetTheme.tokens.primary }}
                  />
                  <span
                    className="h-5 w-5 rounded-full border-[1.6px] border-(--sk-line)"
                    style={{ backgroundColor: presetTheme.tokens.background }}
                  />
                  <span
                    className="h-5 w-5 rounded-full border-[1.6px] border-(--sk-line)"
                    style={{ backgroundColor: presetTheme.tokens.foreground }}
                  />
                </div>
                <p className="font-hand text-sm text-(--sk-text)">
                  {tSettings(presetTheme.labelKey)}
                </p>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
